default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  host: locahost
  database: skapp_development
  username: admin
  password: admin

test:
  <<: *default
  host: localhost
  database: skapp_test
  username: admin
  password: admin

production:
  <<: *default
  database: skapp_production
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
